#!/usr/bin/env python3
"""
post-process-palette.py

Wraps the raw CSS output from sass (palette-shim.scss compilation) into a
properly headed ubuntu-palette.less file.

Usage:
    sass palette-shim.scss ... | python3 scripts/post-process-palette.py \
        > resources/skins.ubuntu.styles/ubuntu-palette.less
"""

import os
import re
import sys
from datetime import date

VANILLA_SOURCE = (
    "https://github.com/canonical/vanilla-framework"
    "/blob/main/scss/_settings_colors.scss"
)

# Set by the workflow's VANILLA_REF env var; falls back gracefully for local runs.
vanilla_ref = os.environ.get("VANILLA_REF", "") or "(unknown — set VANILLA_REF env var for local runs)"

css = sys.stdin.read()

root_match = re.search(r"(:root \{.*?\})", css, re.DOTALL)
if not root_match:
    sys.exit("ERROR: no :root { } block found in compiled CSS")

root_block = root_match.group(1)

# sass may emit empty-comment artefacts on the first line; strip them
root_block = re.sub(r"^/\*.*?\*/\s*", "", root_block, flags=re.DOTALL)

output = f"""\
/**
 * Ubuntu skin — Vanilla Framework colour palette
 *
 * AUTO-GENERATED — do not edit this file manually.
 * Regenerate by triggering the "Update Vanilla Framework palette" workflow
 * on the palette-tooling branch.
 *
 * Source:    {VANILLA_SOURCE}
 * Ref:       {vanilla_ref}
 * Generated: {date.today().isoformat()}
 */

/* stylelint-disable color-no-invalid-hex */

{root_block}
"""

sys.stdout.write(output)
